---
descheduler:
  # helm install descheduler --namespace kube-system descheduler/descheduler -f values.yaml
  # Default values for descheduler.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  image:
    repository: k8s.gcr.io/descheduler/descheduler
    # Overrides the image tag whose default is the chart version
    tag: "v0.20.0"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 256Mi

  nameOverride: ""
  fullnameOverride: ""

  schedule: "*/5 * * * *"
  # startingDeadlineSeconds: 200
  # successfulJobsHistoryLimit: 1
  # failedJobsHistoryLimit: 1

  cmdOptions:
    v: 3
    # evict-local-storage-pods:
    # max-pods-to-evict-per-node: 10
    # node-selector: "key1=value1,key2=value2"

  podAnnotations:
    botkube.io/disable: "true"

  deschedulerPolicy:
    strategies:
      RemoveDuplicates:
        enabled: false
        params:
          removeDuplicates:
            excludeOwnerKinds:
            - "ReplicaSet"
      RemovePodsViolatingNodeTaints:
        enabled: true
      RemovePodsViolatingNodeAffinity:
        enabled: true
        params:
          nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: true
      LowNodeUtilization:
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            thresholds:
              "memory": 20
            targetThresholds:
              "memory": 60
      RemovePodsHavingTooManyRestarts:
        enabled: true
        params:
          podsHavingTooManyRestarts:
            podRestartThreshold: 20
            includingInitContainers: true

  priorityClassName: system-cluster-critical

  nodeSelector:
    beta.kubernetes.io/arch: amd64

  rbac:
    # Specifies whether RBAC resources should be created
    create: true

  podSecurityPolicy:
    # Specifies whether PodSecurityPolicy should be created.
    create: true

  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the fullname template
    name:
