apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBQ2ad0zmKCwM6I+nXpou/WU+cc1p4bUttBDTis4uEvRnvfzNsyDqeLK/5j49jLe3S3jh+BEHJb7nkx+6vtRPhmLTUpjBpm6LgqeFRkmO4p61vng6Z/BZNEG68DqA2CzvB5Th4ubU1DIAihBqpvF1LkfIjb0GwQuNon4M/1CNe5FVzloBh23w8PbSaknO/rfldwxcqcvIC+Ph/dLMXhmMFKgeF6JS0ysQQrm2W/CnPDctMQ9T65JYnYg61S1645u0bsTX54kDeQfODPvxjTVRUjvsgE4QFjvE46g+loL1DI3/RpnDZKcJQSgLk3Pca8llunOrNsdVq8XW50rxemBqrWGJy6lHt/5KXd6SvBqUe27mri8JD3RZcjg6JNmEVLKOtxyB/KUoBmEPm5IBFwGiRMje1gDoiLM/bMlwW3rIxAYwz3nAtio7lfBENP8jw4Em5T6q3nXW2RVVYvHBmptOqeN/58rdRDPfwuI4W2bI4qFjtM5PtboT6Y6WTtpzVQ47uqfsBq1EKfJ0MwN5LuNGiOY0KTiCIuAIKfiWw4QhJfwh5lEaP2Y3N3Ha1/w5Yt/TA+VCFi5pE5BSlwVxZJZgKiBMHBiN26j9R3Xs0l5P7S2pfRtnl4ei7JCgP0DtV7PG4RtH8WlBcqVGv7Tiy9H3St6yIGvs8gsMbNx6uhIwyRmLNPh7DdNG3iJKF1xFQFfaJ2ES9h4VgJPbd/ZHvXXDqlARo5vpCKKubLmwvRKWMw8SQfw6w=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-token
      namespace: cert-manager
    type: Opaque
