---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-ombi
  namespace: media
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-ombi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
