apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-heimdall
spec:
  storageClassName: ""
  claimRef:
    name: nfs-pvc-heimdall
    namespace: default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.40.2
    path: "/mnt/vault/Kubernetes/pvc/heimdall"
