---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-heimdall
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
