---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-heimdall
  namespace: default
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-heimdall
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
