apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-tautulli
spec:
  storageClassName: ""
  claimRef:
    name: nfs-pvc-tautulli
    namespace: media
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.40.2
    path: "/mnt/vault/Kubernetes/pvc/tautulli"
