---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
      - name: external-dns
        image: bitnami/external-dns:0.7.6-debian-10-r91
        args:
        - --log-level=debug
        - --log-format=text
        - --namespace=services
        - --annotation-filter=kubernetes.io/ingress.class=nginx
        - --domain-filter=technolab.cloud
        - --zone-id-filter=0ffc4d9b52f75751e4dab83abb5c048b
        - --provider=cloudflare
        - --cloudflare-proxied
        - --registry=txt
        - --txt-owner-id=technolab-external-dns
        - --txt-prefix=txt-
        - --policy=sync
        - --interval=1m
        env:
        - name: EXTERNAL_DNS_SOURCE
          value: |-
            ingress
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: cloudflare-api-token
              name: external-dns-cloudflare
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              key: cloudflare-email
              name: external-dns-cloudflare
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 200Mi
        ports:
        - name: http
          containerPort: 7979
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 2
          successThreshold: 1
