---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-secret
  namespace: kube-system
spec:
  encryptedData:
    slack-hook: AgBPBiEpNz18/kWpptI/Om1F5Dfe94gagEwShnprmanF5X8gSrNEfSuDdJp0jSI+LGPSiAeSIiwX1KgPJem0zwJ7//dHmPtx35VwRTFuQ4fvslORv3ysJlcnZACZIinrfZqDmewWvpQRs44n3kKZ/nlSUwHBWMe+JrKKzuOnl/r0j47wZLbTg50vKABSeBTIqjNnBLZjG4HVCDKUsShY6ODu90MFYSRQOjoCJG0LdUklo+4aUsbh3cIZQTL43hT6uigmHBciTj65jzAxwhxnzgToYie8CarEfkxLTsUFuoytRLpR7hi7wVy9uemxDPzvzTVjDLpgV9wOKXD1h/e+fmvc7mVEkiVEi4yAuen9iFQhyETtFifui9LwcvrQ/YpajrEMLtCFM8m/SQmjxwdmDa7ncfNvntw0sTDhTFC24lzkmtLT1+MayrHoqVP4csCAah5qONZET31ulr7tJj/FmBNfIqwlik1WqeeKeT79MhhM8i0N53cPDoYlKBSRxWR38oxJgbsnOfBbedW31KN9BL0SlH4g/DAqb6TYjtomhj3HpnJWryP04jzGMjRFPAhkPwQfz4Rp9t/oCQces5FGyp36A2UzT/VSeMKMVwYwHqkOkjqikpRXMrrFdxE/pHNPOIzm00GUJQTQIH3mLKyz43vOa98a6ItftzNz2byBqVOjoIhFPoTmEpyn20W4yg9Hw+tBHaMBDT+PiHo1l8Yrx+pdx7+YR0X06L3CNRbVv7SqbYUQS5URW9RJwMOHCaf4JHYUXn6sZCta2Sou6CdjCILXGHdXpAkjk3nz0EOB+200NHs=
  template:
    metadata:
      creationTimestamp: null
      name: kured-secret
      namespace: kube-system
    type: Opaque
