---
# helm install kured kured/kured -n kube-system -f values.yaml
image:
  repository: weaveworks/kured
  tag: 1.6.1
  pullPolicy: IfNotPresent
  pullSecrets: []

updateStrategy: OnDelete
#  requires RollingUpdate updateStrategy
maxUnavailable: 1

podAnnotations: {}

extraArgs: {}

extraEnvVars:
  - name: SLACK_HOOK_URL
    valueFrom:
      secretKeyRef:
        name: kured-secret
        key: slack-hook

configuration:
  lockTtl: 0                 # force clean annotation after this ammount of time (default 0, disabled)
  alertFilterRegexp: ""      # alert names to ignore when checking for active alerts
  blockingPodSelector: []    # label selector identifying pods whose presence should prevent reboots
  endTime: "06:00"                # only reboot before this time of day (default "23:59")
  lockAnnotation: ""         # annotation in which to record locking node (default "weave.works/kured-node-lock")
  period: ""                 # reboot check period (default 1h0m0s)
  prometheusUrl: ""          # Prometheus instance to probe for active alerts
  rebootDays: []             # only reboot on these days (default [su,mo,tu,we,th,fr,sa])
  rebootSentinel: "/var/run/reboot-required"         # path to file whose existence signals need to reboot (default "/var/run/reboot-required")
  slackChannel: ""           # slack channel for reboot notfications
  slackHookUrl: "${SLACK_HOOK_URL}"  # slack hook URL for reboot notfications
  slackUsername: "kured"          # slack username for reboot notfications (default "kured")
  messageTemplateDrain: "Draining node %s from my k3s cluster"   # slack message template when notifying about a node being drained (default "Draining node %s")
  messageTemplateReboot: "Rebooting node %s from my k3s cluster"  # slack message template when notifying about a node being rebooted (default "Rebooted node %s")
  startTime: "02:00"              # only reboot after this time of day (default "0:00")
  timeZone: "Europe/Berlin"               # time-zone to use (valid zones from "time" golang package)

rbac:
  create: true

serviceAccount:
  create: true
  name:

podSecurityPolicy:
  create: false

resources: {}

metrics:
  create: false
  namespace: ""
  labels: {}
  interval: 60s
  scrapeTimeout: ""

service:
  create: false
  port: 8080
  annotations: {}
  name: ""

podLabels: {}

priorityClassName: ""

tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

affinity: {}

nodeSelector: {}
