---
# helm install -n mailhog mailhog codecentric/mailhog -f values.yml
mailhog:
  image:
    repository: docker.io/mailhog/mailhog
    tag: "v1.0.1"
    pullPolicy: IfNotPresent

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    labels: {}
    hosts:
      - host: mailhog.home-lab.io
        paths: ["/"]

  auth:
    enabled: true
    existingSecret: "mailhog-secret"
    fileName: auth.txt
    fileContents: ""

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
