---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-adguard
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
