---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-firefly
  namespace: default
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-firefly
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
