apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-code-server
spec:
  storageClassName: ""
  claimRef:
    name: nfs-pvc-code-server
    namespace: services
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.40.2
    path: "/mnt/vault/Kubernetes/pvc/code-server"
