---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBqxYQ0N4pJuHSH6MSYDRC5pzzmKg9lhYsrEJyHmVkfsZswfkdfOYgOU8yi9qy0xRQpCkQv2f13rIpZuFH0t3l/htukIGijB1o2UHOHvOitk9bIABqmZwfuH4aJRcYqIxNr+EIn4jjQNxyHGeTpiiGci74s3arHV+0dy4Vr8I+EtgyIH7W5noobbo/i2RhSUNJdJuglvx80h9tW4WgoEALh6mLXOVjlMaK/XDc3pSnTZ06bgq9++gnqlq2toWB4O2CS82ZRhfDIRTTrP2M78NU9Cwol56I+ZTGIYZk6W10R5WOumpdqb6+musEjrZc2MhCB9SZ2ob5a73JIZq22HLXf3NDefqZKMZ5ZS0zRCf12szKOSShsDsgd0wPF2g/M66+tHzZ2K83g0LEzZyhDcVh40zq0OewnhV3P6IevqVzFjsMjgsQxKQhMmYrSniu0ToKbngqBnOKGjWhZWSrTe0X9PmsdmmDmKf+y/nWbDxaJqOApMC6VCk8s/1dS+cFVFEsFgzknqOMT7PDf+VFMer9Rc+b79MH9fTPdxm5qr/zGsPPA6Hh+Z6aApiTlwxLHTiuQMCUGFhRKg4MyeANypmUXWytDoAKMR/BSJ8IId6wjuuHdPxvPDeaa6J1X9YQdLk2kAj6X2qXhNoKxxmNr5jS8ln+yaQg4RsFBXdohrpZs1dsLAq4VOqydYFzkf/XxPLHY02MZPD6/ni7LEgZrNGpBJey/g9rEatJZ0FDMHaEXKjtDo3IXBxXBhOMSREQfuWHQG9Dq2lRufQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
