---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: jackett
spec:
  project: default

  source:
    repoURL: https://github.com/ebrianne/k3s-at-home.git
    targetRevision: HEAD
    path: apps/media/jackett/

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
