---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: linkerd-viz
spec:
  project: default

  source:
    repoURL: https://github.com/ebrianne/k3s-at-home.git
    targetRevision: HEAD
    path: apps/linkerd/linkerd2-viz/
    helm:
      releaseName: linkerd-viz
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
