---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: linkerd
spec:
  project: default

  source:
    repoURL: https://github.com/ebrianne/k3s-at-home.git
    targetRevision: HEAD
    path: apps/linkerd/linkerd2/
    helm:
      releaseName: linkerd2
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd

  syncPolicy:
    automated:
      prune: false
      selfHeal: true

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: linkerd-proxy-injector-tls
      jsonPointers:
        - /data/crt.pem
        - /data/key.pem
    - group: ""
      kind: Secret
      name: linkerd-sp-validator-tls
      jsonPointers:
        - /data/crt.pem
        - /data/key.pem
    - group: ""
      kind: Secret
      name: linkerd-tap-tls
      jsonPointers:
        - /data/crt.pem
        - /data/key.pem
    - group: admissionregistration.k8s.io/v1beta1
      kind: MutatingWebhookConfiguration
      name: linkerd-proxy-injector-webhook-config
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io/v1beta1
      kind: ValidatingWebhookConfiguration
      name: linkerd-sp-validator-webhook-config
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: apiregistration.k8s.io/v1
      kind: APIService
      name: v1alpha1.tap.linkerd.io
      jsonPointers:
        - /spec/caBundle
