
---
- name: Create master server with k3s {{ k3s_version }} using k3sup
  delegate_to: localhost
  shell: |
    k3sup install --ip {{ master_ip }} --user {{ ansible_user }} --k3s-version {{ k3s_version }} --local-path $HOME/.kube/config --context k3s-test  --cluster --tls-san {{ tls_san }} --k3s-extra-args={{ server-extra-args | default "" }}