apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-jackett
spec:
  storageClassName: ""
  claimRef:
    name: nfs-pvc-jackett
    namespace: media
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.40.2
    path: "/mnt/vault/Kubernetes/pvc/jackett"
