---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-jackett
  namespace: media
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-jackett
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
