---
apiVersion: v2
type: application
name: argocd
version: 2.5.7
appVersion: v2.5.7
dependencies:
  - name: rancher
    repository: https://releases.rancher.com/server-charts/stable
    version: 2.5.7
