---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nextcloud-cron-job
  namespace: services
  labels:
    app: nextcloud
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 100
      template:
        metadata:
          name: nextcloud-curl-job
          labels:
            app: nextcloud
          annotations:
            botkube.io/disable: 'true'
            linkerd.io/inject: disabled
        spec:
          restartPolicy: Never
          containers:
            - name: nextcloud-cron-job
              image: curlimages/curl:7.77.0
              imagePullPolicy: IfNotPresent
              command: ["curl"]
              args:
                - "--fail"
                - "-L"
                - "https://nextcloud.technolab.cloud/cron.php"
              resources: {}
