---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nextcloud-cron-job
  namespace: services
  labels:
    app: nextcloud
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: nextcloud-cron-job
              image: ebrianne/nextcloud:21.0.1-apache
              imagePullPolicy: IfNotPresent
              securityContext:
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                privileged: false
              command: ["curl"]
              args:
                - "--fail"
                - "-L"
                - "https://nextcloud.technolab.cloud/cron.php"
              resources: {}
