---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      securityContext:
        fsGroup: 33
      containers:
      - name: redis
        image: redis:alpine
        command:
        - redis-server
        - "/etc/redis/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 20
          periodSeconds: 3
        volumeMounts:
        - name: redis-conf
          mountPath: /etc/redis/redis.conf
          readOnly: true
          subPath: redis.conf
        - name: redis-data
          mountPath: /data
      - name: nextcloud
        image: ebrianne/nextcloud:20.0.7-apache
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: POSTGRES_HOST
          value: "10.0.40.11"
        - name: POSTGRES_DB
          value: "nextcloud"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: db_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: db_password
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: nextcloud-username
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: nextcloud-password
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "nextcloud.technolab.duckdns.org"
        - name: NEXTCLOUD_UPDATE
          value: "0"
        - name: NEXTCLOUD_DATA_DIR
          value: "/data"
        - name: NEXTCLOUD_TABLE_PREFIX
          value: "nc_"
        - name: REDIS_HOST
          value: "localhost"
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: PHP_UPLOAD_LIMIT
          value: "2G"
        livenessProbe:
          httpGet:
            path: /status.php
            port: http
            httpHeaders:
            - name: Host
              value: nextcloud.technolab.duckdns.org
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status.php
            port: http
            httpHeaders:
            - name: Host
              value: nextcloud.technolab.duckdns.org
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /status.php
            port: http
            httpHeaders:
            - name: Host
              value: nextcloud.technolab.duckdns.org
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        volumeMounts:
        - name: nextcloud-root
          mountPath: /var/www/html
          subPath: html
        - name: nextcloud-root
          mountPath: /var/www/html/config
          subPath: config
        - name: nextcloud-root
          mountPath: /var/www/html/custom_apps
          subPath: custom_apps
        - name: nextcloud-root
          mountPath: /var/www/html/themes
          subPath: themes
        - name: nextcloud-data
          mountPath: /data
        - name: nextcloud-config
          mountPath: /var/www/html/config/redis.config.php
          subPath: redis.config.php
        - name: nextcloud-config
          mountPath: /var/www/html/config/custom.config.php
          subPath: custom.config.php
        - name: nextcloud-config
          mountPath: /var/www/html/config/.htaccess
          subPath: .htaccess
        - name: nextcloud-config
          mountPath: /var/www/html/config/apache-pretty-urls.config.php
          subPath: apache-pretty-urls.config.php
        - name: nextcloud-config
          mountPath: /var/www/html/config/apcu.config.php
          subPath: apcu.config.php
        - name: nextcloud-config
          mountPath: /var/www/html/config/apps.config.php
          subPath: apps.config.php
      - name: nextcloud-exporter
        image: xperimental/nextcloud-exporter:v0.4.0
        imagePullPolicy: IfNotPresent
        env:
        - name: NEXTCLOUD_USERNAME
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: nextcloud-username
        - name: NEXTCLOUD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: nextcloud-password
        - name: NEXTCLOUD_SERVER
          value: http://localhost
        - name: NEXTCLOUD_TIMEOUT
          value: "5s"
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - name: metrics
          containerPort: 9205
      volumes:
      - name: nextcloud-root
        persistentVolumeClaim:
          claimName: longhorn-pvc-nextcloud
      - name: nextcloud-config
        configMap:
          name: nextcloud-config
      - name: nextcloud-data
        nfs:
          server: "10.0.40.2"
          path: "/mnt/vault/Nextcloud"
      - name: redis-data
        emptyDir: {}
      - name: redis-conf
        configMap:
          name: nextcloud-config
