---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-nextcloud
  namespace: services
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
