---
gitlab-runner:
  imagePullPolicy: IfNotPresent
  replicas: 1
  gitlabUrl: https://gitlab.technolab.cloud/
  terminationGracePeriodSeconds: 3600
  checkInterval: 30
  unregisterRunners: true
  concurrent: 4
  logLevel: info
  logFormat: text
  rbac:
    create: true
  metrics:
    enabled: false
  runners:
    secret: gitlab-runner-secrets
    privileged: true
    locked: false
    cache:
      secretName: gitlab-runner-secrets
      cacheType: s3
      cachePath: "runner"
      cacheShared: true
      s3ServerAddress: 10.0.40.2:9001
      s3BucketName: runners-cache
      s3BucketLocation: minio
      s3CacheInsecure: true
    config: |
      [[runners]]
      name = "gitlab-runner"
      url = "https://gitlab.technolab.cloud/"
      shell = "bash"
      limit = 0
      executor = "kubernetes"
      [runners.cache]
        Type = "s3"
        Path = "runner"
        Shared = true
        [runners.cache.s3]
          ServerAddress = "10.0.40.2:9001"
          BucketName = "runners-cache"
          BucketLocation = "minio"
          Insecure = true
      [runners.kubernetes]
        image = "ubuntu:20.04"
        namespace = "gitlab-runner"
        privileged = true
        pull_policy = "if-not-present"
        dns_policy = "cluster-first"
        poll_interval = 5
        poll_timeout = 3600
        cpu_limit = "1"
        memory_limit = "1Gi"
        service_cpu_limit = "1"
        service_memory_limit = "1Gi"
        helper_cpu_limit = "500m"
        helper_memory_limit = "100Mi"
