---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  namespace: media
  labels:
    app: deluge
  annotations:
    backup.velero.io/backup-volumes: config
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      initContainers:
      - name: sysctl-ipv6
        image: busybox:1.33.0
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - sysctl -w net.ipv6.conf.all.disable_ipv6=1
        securityContext:
          privileged: true
      containers:
      - name: deluge
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        image: ebrianne/docker-deluge-openvpn:v1.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8112
          name: deluge
        env:
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        - name: TZ
          value: "Europe/Berlin"
        - name: OPENVPN_PROVIDER
          value: "NORDVPN"
        - name: NORDVPN_COUNTRY
          value: "NL"
        - name: NORDVPN_CATEGORY
          value: "legacy_p2p"
        - name: NORDVPN_PROTOCOL
          value: "udp"
        - name: CREATE_TUN_DEVICE
          value: "true"
        - name: LOCAL_NETWORK
          value: "10.96.0.0/16,10.69.0.0/16"
        - name: ENABLE_UFW
          value: "true"
        - name: UFW_ALLOW_GW_NET
          value: "true"
        - name: DROP_DEFAULT_ROUTE
          value: "false"
        - name: OPENVPN_OPTS
          value: "--inactive 3600 --ping 10 --ping-exit 60"
        - name: OPENVPN_USERNAME
          valueFrom:
            secretKeyRef:
              name: deluge-secret
              key: OPENVPN_USERNAME
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: deluge-secret
              key: OPENVPN_PASSWORD
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: 1
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: nfs-pvc-deluge
      - name: downloads
        nfs:
          server: 10.0.40.2
          path: /mnt/vault/Media/downloads
