---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-deluge
  namespace: media
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-deluge
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
