---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: ldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
      - name: openldap
        image: ebrianne/openldap:2.4.57
        imagePullPolicy: "IfNotPresent"
        env:
          - name: LDAP_ADMIN_USERNAME
            value: "admin"
          - name: LDAP_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: adminpassword
                name: openldap-secret
          - name: LDAP_USERS
            valueFrom:
              secretKeyRef:
                key: users
                name: openldap-secret
          - name: LDAP_PASSWORDS
            valueFrom:
              secretKeyRef:
                key: passwords
                name: openldap-secret
        ports:
          - name: tcp-ldap
            containerPort: 1389