---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: ldap
  labels:
    app: openldap
spec:
  type: ClusterIP
  ports:
    - name: ldap
      port: 389
      targetPort: ldap
  selector:
    app: openldap
