---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: services
  labels:
    app: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.13.3
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_NAME
          value: Gitea
        - name: RUN_MODE
          value: prod
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: ROOT_URL
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: root_url
        - name: SSH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: ssh_domain
        - name: SSH_PORT
          value: "22"
        - name: HTTP_PORT
          value: "3000"
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: 10.0.40.11:5432
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: postgres_db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: postgres_user
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-secret
              key: postgres_password
        - name: DISABLE_REGISTRATION
          value: "true"
        - name: REQUIRE_SIGNIN_VIEW
          value: "true"
        ports:
        - containerPort: 3000
          name: gitea-http
        - containerPort: 22
          name: gitea-ssh
        volumeMounts:
        - name: gitea-data
          mountPath: /data
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: longhorn-pvc-gitea
