---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-gitea
  namespace: services
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
