apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-redis
spec:
  storageClassName: ""
  claimRef:
    name: nfs-pvc-redis
    namespace: redis
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.40.2
    path: "/mnt/vault/Kubernetes/redis"
