---
ansible_python_interpreter: /usr/bin/python3
ansible_user: ansible
localhost_user: user
systemd_dir: /etc/init.d

kube_vip:
  tag: 0.3.5
  ip: "{{ groups['vip'][0] }}"
  interface: ens18

k3s:
  bootstrap_master_ip: "{{ groups['masters'][0] }}"
  version: v1.21.1+k3s1
  user: root
  tls_san: "{{ kube_vip.ip }}"
  cluster_cidr: 10.69.0.0/16
  cluster_dns: 10.96.0.10
  service_cidr: 10.96.0.0/16
  master_taint: node-role.kubernetes.io/master=true:NoSchedule

metallb:
  tag: v0.9.6
  ip_range: 10.0.40.65-10.0.40.70
