---
ansible_python_interpreter: /usr/bin/python3
ansible_user: root
localhost_user: ebrianne
systemd_dir: /etc/init.d

proxmox:
  masters: 
    number: 2
    ram: 2G
    disk: 10G
  workers:
    number: 1
    ram: 2G
    disk: 10G
  dist: alpine

kube_vip:
  tag: 0.3.3
  ip: "{{ groups['vip'][0] }}"
  interface: eth0
  
k3s:
  bootstrap_master_ip: "{{ groups['masters'][0] }}"
  version: v1.20.5+k3s1
  user: root
  tls_san: "{{ kube_vip.ip }}"
  cluster_cidr: 10.69.0.0/16
  cluster_dns: 10.96.0.10
  service_cidr: 10.96.0.0/16
  master_taint: node-role.kubernetes.io/master=true:NoSchedule

metallb:
  tag: v0.9.6
  ip_range: 10.0.40.65-10.0.40.70