---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-website
  namespace: services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-website
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
