---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: nginx-website
  name: nginx-website
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/ingress.allow-http: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: services-nc-headers@kubernetescrd
    external-dns.alpha.kubernetes.io/hostname: ebrianne.technolab.cloud,www.technolab.cloud
    external-dns.alpha.kubernetes.io/target: technolab.cloud
spec:
  rules:
  - host: ebrianne.technolab.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-website
          servicePort: http
  - host: www.technolab.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-website
          servicePort: http
  - host: technolab.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-website
          servicePort: http
  tls:
  - hosts:
    - ebrianne.technolab.cloud
    - technolab.cloud
    - www.technolab.cloud
    secretName: services-technolab-cloudflare-org-tls
