apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reg-creds
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgAd2wfze51hc/dh9YDI2T56F3WTuV89GJ2HV7h8+Vx9XtnkcwFL5R3O67inZWeWI6/RxTmE18huFxnU0HTZq3IjaVADtit7bHF1aBIgzIOJwcH8KAQzZucDTcfVhl99QSzpnaQCSNZx3Eflt4ZV0d0r3iMYZT+wRsamWv1avBZd3WiMw1j8C8LNfU9MYgxXPQxp87MBHgOXKZZdQ6kTWhSM7b62ER+v9XBF1itMDQF0CLndcoaapH3n/gQuTm38AzpnMWgIUm7fP6tzrhnP16nS715bs/BYzQHsNF4RiTxz9G6mHobZOZXF5ZtyBcXC9+gOmkhsOWuwCammwtz36FDqALgV+/EMEDpksBWVu9+8eNbjxi6G9oYw5tnC7jgrmretVIT+wmAMndzY7Mk1qLTvGpN+NE57Pn9Xis95QERZ2tjzEyB5P4Hzz8p56OoCbdoVCFXWCnCgP3MJWA5Q7TvMwu7ILBTM0HSjOOKMsYwoCKh6HXUWEfKilNpKLHmtledlG2azhR3UDkKVdAglQ2Xujd7C0fCeMTzlGuJSnYJzxL031OrEvfVmVVU/X5c3Ieq50/k5weiPo9s9Q1+Tm4ho8znAD13tidkoYSlQfhv7d4Glseym+D4OUcD43RaYkX6Y2pVHDcuTU1aIKQQ63x32D7/RpvoxrQkcoptRfy/wjfGWRI40jY2UzJkgIZ1ZodCHCb7v24sEC7MpjTxnmqNZv8QgxdRdk7+4AOATM2gzRroNcrEKVblEMArw2du0koC71mJVe9+S/1uVxraqxbXrrWERg3o5dWovAVnoFS7baGTf5TBbbfQzyOSx8028Aj6wn7piXcXEQXqRN1//vc8Hl7YdlJZMjTB8DdEokoM+IvMkUoPr3/nfujX/BAgSFKrUHkgVk1W/XXrrwep3P70rwUsf05vhE9y1ecCn2oluh1wtHvibNSkceiC09HxDfD++j38HAIrzTh70xGlZwJ7650+9DF0OQfCZIp/tFwvLp9klP0ZBW+awtz8orAX98gHXLm/GFBFqE7ZsG7e7W2Uf5udN48ez/bxkeryEkPjR1LtlLHSxQT0zx8KEOSzd3KvaEglB7D4z6YA8IhwOB3oYQIhoUT4nVODAl+x8dRgIe5kAOlZTOKytetcf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: reg-creds
      namespace: services
    type: kubernetes.io/dockerconfigjson
