---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: authelia
  namespace: services
  labels:
    app: authelia
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
spec:
  rules:
  - host: authelia.technolab.duckdns.org
    http:
      paths:
      - path: /
        backend:
          serviceName: authelia
          servicePort: 9091
  tls:
  - hosts:
    - authelia.technolab.duckdns.org
    secretName: services-technolab-duckdns-org-tls
