---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authelia-auth
  namespace: services
spec:
  forwardAuth:
    address: http://authelia.services.svc.cluster.local/api/verify?rd=https://authelia.technolab.cloud/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
