---
flaresolverr:
  # helm install -n media flaresolverr k8s-at-home/flaresolverr -f values.yaml
  image:
    repository: flaresolverr/flaresolverr
    pullPolicy: IfNotPresent
    tag: v1.2.8

  strategy:
    type: Recreate

  env:
    TZ: "Europe/Berlin"
    LOG_LEVEL: "info"

  service:
    main:
      ports:
        http:
          port: 8191

  ingress:
    main:
      enabled: false

  nodeSelector: {}

  tolerations: []
