apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    traefik.yaml: AgBfkiVElCUD09kkXHYM0C09XlB2CMQJKNM4s4HUmiqAbkonyIZOBEe/g+7saouVdAANaey70Bk1nuIEVPWdNwbI4626wBI4Y2KOoPPkTZsQGAMeEhdtVYoRG7wgXgPfdli28POpbWuIJ500mHTNGN5+b20NkYY5NFdNKj0p/6I5nJBLh9hoSme9SKMZ4xg1nYqgP7Rd9tmz3mrkDZNocYymdlGnw2ndMYcRdygB+lnyaMEfAg51AN4D2XrvBknUOLc6VGVPx8eMEt6rYSTq4skoA9K0ikGk8dhHFdX+C07wP+0dAcD6eFabHm47ISUJwCh5dc26Fw79tGTMbIBgZ3c9JqCCxbgMwRbXrRxqGvFskm2Z+vpfe5zhxzs+5CUPZ5XsVBTXZc7P+lWXB5pkrTsXO4HwKcy6QqHvwQvs5S78t5EwI5xTBa3gRNjzEMMBrosrUHUjJbpkYz/8Rs/sNDC7lBKdb2YnrhG4XIoaxTRqDBKXtb4wuDL8MhZ0TTQkSpu/otQNQruasdAsfkwTlZxbH5k5suoOhnwDFnnnqtAGW9/N8v2WtckiC/YloQHG2PWIBRuyCdSat4kNGhO0RvaMr5Sk3LFtG0tiGXZzltkZd1lnXwoNYk0eDv5NZatyrIdHgw0xSI5HafWqCw8fesSuL9ZPfVurlN1wyfKHbVaUBnKlKuB+q1JRP3dpKBJUAHqt6G+E1WW2V9HKlNr/w+aUa/4qBOKBmVFSF5TTUZ7+LocgJVCo2PIW30v34uy+O1H93TzvTWdznxfZkP26SGTtGsvvguO3Cyb+Izh/t2sOQBvjOjYFGPEvlRzEmsTNyNzkSA4RYSqPQrqGb+/uhsWCtIa3lb7t0qsGl8aXuKqXS6JWXN4hnMgaWyrDHmKaLy/0n1dsx/IKlh4QtJQLAGL225FCr2q1XPMSlsuIUSvpCr5Xa/4X9k8y6hft5IpAvaQ23XxqU2tJubBjyPShLypGwyobb8FpHb/0cHIDDjzShG+RzpqHLbkgHSn7Xpqa+WBt0BWiRY0Maei8bi1mIyevGMFNpnkGUTxAs8pWTaV7agzA9NxlGbt10qim1Z/11HdVgDDRWMuWxYaC/iHYptUcMcevK5W7RzjZSFH7BqAsOPw+B5cJ/9PPQ1QeaklRdF/MQZJGTCqGpBsJb1T0JP62I+izHvr5dVvI491CoJ5+suocMy67jOhHw0/K1Ti33jY+XC25ZgCYCWlc1m5nFq9DiItT5pThT/I7nYy8JfGKiuoySk6BkqMD6Tjb/w+XTnLD0i2jriOnWvkuxzZd+pYr3Y3mNzPfs/Aodlra8CqmM0Oc1XvMT8cswodBlM+kfNfUWiSNqAU7K7zf5b92rHGTktqH5XVErdzRjHCGosq0ssBzyrVRIO3asEL1SufLQ1OlIme+x7QOgVAELAYSI4rvcF2mze3rORo6VeuAMRsQKLioi97V2VTezHUoxZhaWlqYn+3rnBD6S2qEVVJR/0wixDVOJ9hOvQrN7upANxYyNIgetdVUah9LeqeUBMM9pmmRlEmBhk2NR5uDEhoCDBxiOjmjmcFNQYyn+O+eqPDEk3BvvZ4A30ZPefPGMRyKuDamIfqmyQ+n6hgahYmG3B3hDTZ8vUHUCgZ0W8G3rcx4X3jzq+qdSpTiSrxlxEvE62+9N/GHqM6YE5kFNWer2K8g8Rtv0l6Ggi4IlTet1TU6xmqsn6jF0+h7a7c+JvVvV4kgxum9Ls5ks+usV5QPDnK5GQZhqfnyNQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: traefik
      name: traefik-secret
      namespace: kube-system
    type: Opaque
