apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    traefik.yaml: AgAS2loHm/E5xZCtRASTM2tS3n3/Ygcazo6/VottkhgMlrvTEjVEIUKgSzN4hYbzMa98SY53XsSrQW37oXQby/6MSSt5tO8zMmqxENmNdi6C6k/mdxbhEJ6JfIoSqH4KFAgxLIfGEuhI8pZdAhOEOvUaRmTqpLLS3NLawY80BSHE2w8UsGyUJUZgJoYa0owrtnFJhKc3AmxN3PyQynLFGdNh9sUtsS5tFHhNKD3sNNibfaGp+0F31TP3z7xB6ZlpZc/UGkvpCU7CtmX3MvYBHYAIv7tj/mx+hbFyxOLv8snfhAA61T/ktV5RfcsfYOIBrNSMRiAb3G7WLB5O1r4aX7LbyyMKTnKCZwamM5NTYMPbXRGOSabktemD0ybzk9mJDUyWhf0hUEJ+ODx2l1Vy45XvdR71WMEtTZuqdUbdQcXb0DTUuBUwrjNw9Oexal4llkBHK7Xkjhqm4bvLUVoLLUHUpzjUXMylYJCZByGdr2vrux2tW8aGW2dPGNRqAmhGEnQh1lrxcCOJGtzmktUVsuo3xfyFejGCAINNC1tQ4SWwdoinlOy0lmyGJ/cnmt5iy3DYxJOxMa8LNL8uWH+HWxE7vi6uWy/pzZsZdjAcLBf1JKIgg67G/650i8OHVOG5mDzK9qByrZGpUCPwC7k79U9ZWKlkSmV11ZUIUhcziyf9NMx2JCP2+ITL2mNRZAg4XOa0vLmWhBnsjNVCZtt34EAgpo1cnFFqBTAeQJ2VNTAwPlRD+YVEZJkTaUv7tWWIXrBfa6B8fIYgT7y+z9H/aeO4p3jOeHEuIEbFNEMzr5HQw5eHdmLPdaHimjhwrOK6AyW4UFiTGMl1300LOpbb6oiduoEtQpOGDJ5zDORY9RoqRPEjODDibIhtXuKT5um9e3ndd00s48rBKmxw9T+wEEE9iY8py6e227Ge0vuzHYQYvBBqiD1pUAiWnJbCylX8MB2fObqTPNUBUbYeNnR+KDhqK5unuFSM48gL5eeHTypD3NPzNCtFmxxOvHkAZonVXagTLuaWhZIgfgAYCNjK4/TX3HjMogDZJcFKsebnb1puyDIPN1mQCHDzE2gWpAf0OKzlqom6Q0IyNntHXGgPogwJ6bD6jZ8NoEu2QirJ788eihDruSjEPRf9VIYuPunN4+VzFZZmuhQna7Vmau0/isqWewKFMJOb+ceSEiwyeKX9OZRYMpFRMMN2fCLcD4zrJJuzqNCbInZ0R7iv597A7fMLdtON3qc/UIMn0MZ5jRSI+xN8wtrVQrOpTY6jabgzN9hsS5/aWgXbPEdfO+ZCEI7pXnGcGvVFW8Q9QLm2I9ASnyvSp9ML/e9GNsKCiMPoR0WFArfk5NqKugs0xGJZyzZt6lSC4IgqkBOoOHohzVFfkLXhEIoJRLKK/2FOXY/3gIlLbXbrhV4O5eYXJABtv1HUIXjNpg3uC8Ox9N0x6W/G4S5msu1lnRm6mGl8P7i3F8PgJ9BiaB7kF7r0/vo2CgcxPCmAqIswObIj5JoIzzMeFG6oD/dI+NSeZ91P37FbMFo/IvkjM2Q1/La63FlCV30xcSJ9hTIqzumyoHQIj37/mN9p/4BXM6VQy/bQwWLa/Bg6pLhbTeCeAnifSfZRfyAFpL+LQdufXrlJqk1g5YkmwEuXYegb6qGzkrFHAFNZJM5YB9jAu9ZKODNGnsHze7qy7xL4rW/mp01vO2QceHif000oQJNyRlhkmjhmUKL1txdx4I5eIWyIBFSxNzirn2FaSqm/MhMMMG7DFYgLfgD8XtBo9pQZcubwYNCN9MMRIeloMGxXFMMPem4Ahd7fCKybt/7LQeJMixNyceATdu+PFU9aIgMB1H0zqWG6MxGTphBz4Uaf6iGwD+dElprvufPxSs4AorFYdCgEiUm6Mw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: traefik
      name: traefik-secret
      namespace: kube-system
    type: Opaque
