apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    TRAEFIK_PILOT_TOKEN: AgAD0y/vMVfIEts3pu60AkQ1Yx8y7SgxpOjNcphXG3jOo3DhVDqyxiJq3RgVKVKIwtpPBbdlLnAnEJ9IWbjjv7ivSRzBNSAj7JfJ+ZL6dT6r8ndlpCrdX/UIBbqY9iJMMw1KCT0Qp+pbIcxdklAPm+wo1EJwC1oWZb8MGlLc3OEWsnBWXQPZpGHLuk3jT4mC+CEOC7EDPhROdlFC38W1QKE/7z1afP1uxPCY84hGwzlFDZVV8l/a3p6PO2JuTGOpXTis3BHqIjAX+fN99dxQz+YPxs8h7OQOlKVUIsT2Iy6NlTgiejNNEC65e03D0lRcnSiS4zyD65Zug6gB90jq9zzx6IgL/7ls8eeHIbH3yBDbptCd4rRmUvUMVLePZvXpv9F3rV96Ay5wQgGVsf0qyoEV7BqMFMiRS7dV17epiEjH3qFooQLbyJbgwJXY0cbBRnnr7WXUxdp8Wt04mvSUXcw6g0r1NU8DWZskFoGqn/thQQ1Xq2v14FfIKYDmG29Ra0pz87R6mGBTSx6JQpOCDY3SAB6Zyxd6F2EfXTmJHUCYfZcbIB6BPdWt0/LHx3Th6oMNySQN3dFtbw85c/Bz9KiBlQFK1o2tGuS8lrEoeUFn78R7PFmqBlTBHeUphU3U4NkuDsqs9xOFobHNYyIgb2Q8jjwCqBW0bOywtpySeJx9GJvu2vHzzBAgATSZwWzcbTDozYD4yLUN2hXGaPIz8Fb9BW5l7Gzdt8WRSWxl2w4gxuyTc3k=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: traefik
      name: traefik-secret
      namespace: kube-system
    type: Opaque
