apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    traefik.yaml: AgCcg4MKKZ4PfKRAidB3cchGge+uijjeSopqSuAuZl5mMC2ujpjARbbdJo2ELsgNkpHJDj89zjpjiSYV4ejByxVBYXkkDlsylO+jDWPvzzW1L5Btnv5WNf4nut+cUDU/+k50tYYLCR6eV+acWJfSSZGyZ2yu+01eJeXALHpHQ3WZtTeEK8gaZnRAAOV8okbXHeJGIaU9Tjaey4HonUgpKJB8FhRKWNhj96920bu9orK3wxgEmSZUvPIublFDfp8eJykL0kkbkMkciixyoahuDG2BLhxlGuIaSw1IGulJqNU5I9h15SdWK92FMYPt8x4l0W05A7LSgbadadBIf2QXdnArNjb8kqegcuOgiGM8BXhEGU170Nu2dInPipLSpwtc5Uf3RRBDb7QK/koAMWQeUBUhwdFiGwKo0V2Y32ovtqSrWMVIF109mPLTcet8ONjS9tii+xPhpdmKVPgLbfZT77sXkq3mNUuYwIxMp2Z4/dJuK7aKzX1gI+3svzHGsdMi3EDPdXXRqkPxg88SYtpjqc01hR3zTRTIpv6tGWGCQbuTPUrQSGAlzxRxYRl3FuFJoOIfsDMDewPJCtfW/CY1R0yuv+uuriGsIgQxpnr3ZfjQmDPSH2JLo3erMlOy5ba8IZpPSoWZr9ooE4BlLCxOzIfn1WQ1cwYBpSSoJtma00F19KmNIAz3Y9bLcMEduR6A+AnYAhyyfPOuCnzbnXm9dhihxDut/SUZJbF/YhRkwgfIpCIAeeYtbl9ZUaKH5NYCfZ39iGeqUJ1pQiJ+IWVQF3DXn2pRGMleW1D9wblvH9tZMFHn3FT7hDHLnpIKVh3xPndgNgNijxdbj7ihxltg1GRbOWwKWoP3wVMdOX0EfrWly3WkAhe3WX2QDC4pjjpWTbzuowH2MMBGaVthUN7P+WG1oZiGNvo1HrjNzrE4Mhe7QmjDxVeUnCBgTqBpTTX5RrVY4TxkdwFFib76I0BJTf0Eh6gdav00USv8hRQUsKGwH2LEaayTRn2IzLEM4Iin+VID1PebPwRCEUIb3fzXW4p9Z96saoT4QZFkZzQ0ki95L9TqivrUbihHg8DDm6/q3bf9LvlxtY02URDH45z9QC3d/2feLX9rnAhbRTp7el05pk0YQaMopCI6lJNGA6fVjnOI4WLPQolkzpYXf0oZXraCjxp2gSALWj1wP3x+H6sVjO+h+IPzK85Uw576oubTwQ7KpZ4mfxG92fdQt8xB3KTwhKj1t8LetrkSv997hzyUPnwsu6vZNyaVJUruuBTW+CELuzl4K8L9Ys9tYdwmZs8+Fk81jd4poOwc0+y6LoFdv/xivliQrslgDlmHvhmCbXWqOvUC4I4+d6Hxo+FpWNCVUQL6re7PhqlXVYwjBTS4Ni1rsmxmIkmLK8T+Cnm9qmHMtE4lUJYgLLpWZr56KIpDPlXOu94njmgSJiK5yiUKA4MhPiPlTvsSwkV/QfrqocH9XiLkFcbHWfwt9lZ+wQfcTq+oCGCfdemArR4qmOdwy+Gm4GmCMBU8ULVTK6JENJVBTBDgVMYg0SslDN+0OaEq7u37RCgj1MIi9DJhZ3FnRmkAbZK+Hc75migkgxNhXbdMOlPY/GPChztCs/2CcTzaWpKK+gQUpKpQZo8tWj9t5FXwIqRcVBWR+cgB6g7s0Y3PWTmoo0a/LtFtw6i/yvoaH9gewA2f/y43f3Eo0v0JByrdyp53BJVkMteBK+ztOvfLwrV71wCC2JCy+GvD9RnXRzjOEIK1xEcjb8ZeBL3f2U0nDswgaJR5TdS7oXqD4oiGDMZHCvOKk7EMfQLcz8p2JjSWNuVFtmqT0+mNRV4ulZOn7fl+jwTwjm0UMb1CnheQ8YxH3yI1d+xxR2V1mxgu/aFeOl7nMtbf90EUzw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: traefik
      name: traefik-secret
      namespace: kube-system
    type: Opaque
