---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-gitlab
  namespace: services
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-gitlab
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
