falco:
  image:
    registry: docker.io
    repository: falcosecurity/falco
    tag: 0.27.0
    pullPolicy: IfNotPresent
    pullSecrets: []

  docker:
    enabled: false
    socket: /var/run/docker.sock

  containerd:
    enabled: true
    socket: /run/containerd/containerd.sock

  resources: {}

  timezone: Europe/Berlin

  falco:
    logLevel: info
    priority: notice
    logStderr: true
    logSyslog: true

    jsonOutput: true
    jsonIncludeOutputProperty: true

    syslogOutput:
      enabled: false

    stdoutOutput:
      enabled: false

    httpOutput:
      enabled: true
      url: "http://falco-falcosidekick:2801/"

    syscallEventDrops:
      actions:
        - ignore
      rate: 100
      max_burst: 1000

    webserver:
      enabled: false

    grpc:
      enabled: false
    grpcOutput:
      enabled: false

  customRules: {}

  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule

  scc:
    create: false

falcosidekick:
  replicaCount: 1

  image:
    repository: falcosecurity/falcosidekick
    tag: 2.21.0
    pullPolicy: IfNotPresent

  config:
    existingSecret: "falcosidekick-secret"

  ingress:
    enabled: false

  webui:
    enabled: true

    image:
      repository: falcosecurity/falcosidekick-ui
      tag: "v0.2.0"
      pullPolicy: IfNotPresent

    retention: 100

    service:
      type: ClusterIP
      port: 2802

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: falco.home-lab.io
          paths: ["/ui", "/events", "/healthz", "/ws"]

falco-exporter:
  enabled: false
  image:
    repository: falcosecurity/falco-exporter
    tag: 0.5.0
    pullPolicy: IfNotPresent

  falco:
    grpcUnixSocketPath: "unix:///var/run/falco/falco.sock"
    grpcTimeout: 3m

  podSecurityContext:
    fsGroup: 2000

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
