---
kind: ConfigMap
apiVersion: v1
metadata:
  name: coredns-coredns
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coredns
    helm.sh/chart: coredns-1.14.1
    k8s-app: coredns
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: CoreDNS
  annotations:
    meta.helm.sh/release-name: coredns
    meta.helm.sh/release-namespace: kube-system
data:
  Corefile: |-
    .:53 {
        errors
        log
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus 0.0.0.0:9153
        forward . 1.1.1.1
        cache 30
        loop
        reload
        loadbalance
    }

    # home-lab.io:53 {
    #   errors
    #   log
    #   forward . 192.168.10.252
    #   cache 30
    # }

    technolab.duckdns.org:53 {
      errors
      log
      forward . 1.1.1.1
      cache 30
    }
