---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: database
spec:
  encryptedData:
    postgres-password: AgAiCQyKRfQ1CuFPGL0pha9tbO93s6kNGVm5cVgDe4le3QY0N0aSq4KLmnk1OCtyySi/KG3Ax5vwAa8KKMADQSfEc8Uarh0kB8NaXWv3gA2TichJYnC2MqQouxim3ijuKa91bq2+gQQKWDqCfXOoqGMXs4yf7f8F4X7pnFtGRAAxWNG6xJrEIF/+//ANde4ZsFlEUxYF5G7FZ/ahyCw8ip/oiZiWuDVbh4PkguKgJH5CD8BglbNOgDOs+6k+NaKoiyIVNWcx98lD8B2wdP3wyjtMmWaxf5Mk+34C1JEIkOD4RVb8NxZD5IdKs5D+U2ja+jNDmvFlfcFE8dIXEGFgI2NT67YgwA2yYrvNPr8Wg7IRJA581+oiNhIfphvfwX9pPKDw0QNxBpjF7Q+83X/fh9wzpwNogs3KhpB/Wu93q3hDGA1LvGtbKjmeA3IzmbjRKyBPW0ZqUIAtDBIRxmJ2bnbibDP5UMs5V7mzEXF1JcGSN4fIlmBZQXudorngJd/Z2kJZQagMqFmizgepata6ddPyDH7WnyADfVvlPN/lTGnUc0anel6ojltL3JZ0pXy8hY8z19FNVywbC36/3dBlYmf28a+lVsw283JRb4FKS0DPX7rAGdrS8rFhEfAhiuedsnqR9EA98ZliCLNk1wBddY8P7i77x0rlkCG0RwcJHokAkOtL/95q04xQcQDETHXY83A2jPFbl7Ae/t1tVtN1
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: postgres
      name: postgres-secret
      namespace: database
    type: Opaque
