---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  namespace: services
  labels:
    app: dind
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dind
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: dind
        image: docker:19.03.15-dind
        imagePullPolicy: IfNotPresent
        args:
        - --host=tcp://0.0.0.0:2375
        - --tls=false
        - --experimental
        - --insecure-registry=http://harbor.home-lab.io
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        ports:
        - containerPort: 2375
        securityContext:
          privileged: true
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        resources: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dind-storage
        emptyDir: {}
