---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  namespace: services
  labels:
    app: dind
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dind
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: dind
        image: docker:20.10.5-dind
        imagePullPolicy: IfNotPresent
        args:
        - --host=tcp://0.0.0.0:2375
        - --tls=false
        - --experimental
        - --insecure-registry=harbor.home-lab.io
        - --registry-mirror=http://harbor.home-lab.io
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        ports:
        - containerPort: 2375
        securityContext:
          privileged: true
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: 2
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dind-storage
        emptyDir: {}
