---
apiVersion: v1
kind: Service
metadata:
  name: dind
  namespace: services
  labels:
    app: dind
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.40.21
  ports:
    - port: 2375
      protocol: TCP
      name: http
      targetPort: 2375
  selector:
    app: dind
