version: "3"

services:
  radarr:
    image: ghcr.io/linuxserver/radarr:version-3.2.2.5080
    container_name: radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Europe/Berlin
    volumes:
      - /home/ebrianne/radarr/data:/config
      - /nfs/Media/downloads/completed:/downloads
      - /nfs/Media/Movies:/movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr.rule=Host(`radarr.local.technolab.cloud`)"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
      - "traefik.http.routers.radarr-secure.entrypoints=https"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.local.technolab.cloud`)"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
