---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-bazarr
  namespace: media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
