---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-exporter
  namespace: services
spec:
  selector:
    matchLabels:
      app: nextcloud-exporter
  template:
    metadata:
      labels:
        app: nextcloud-exporter
    spec:
      containers:
      - name: nextcloud-exporter
        image: xperimental/nextcloud-exporter:v0.4.0
        imagePullPolicy: IfNotPresent
        env:
        - name: NEXTCLOUD_USERNAME
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: nextcloud-username
        - name: NEXTCLOUD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: nextcloud-password
        - name: NEXTCLOUD_SERVER
          value: https://nextcloud.technolab.duckdns.org
        - name: NEXTCLOUD_TIMEOUT
          value: "5s"
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - name: metrics
          containerPort: 9205
