---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
      annotations:
        backup.velero.io/backup-volumes-excludes: downloads,tv
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:version-3.0.6.1196
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8989
          name: sonarr
        env:
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        - name: TZ
          value: "Europe/Berlin"
        resources: {}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: tv
          mountPath: /tv
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: nfs-pvc-sonarr
      - name: tv
        nfs:
          server: 10.0.40.2
          path: /mnt/vault/Media/Series
      - name: downloads
        nfs:
          server: 10.0.40.2
          path: /mnt/vault/Media/downloads/completed
