---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: metrics-server
spec:
  project: default

  source:
    repoURL: https://github.com/ebrianne/k3s-at-home.git
    targetRevision: HEAD
    path: apps/kube-system/metrics-server

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
