---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prerequisites

- hosts: localhost
  connection: local
  roles:
    - role: k3sup_install

- hosts: master_bootstrap
  roles:
    - role: k3sup_bootstrap
      
- hosts: masters
  become: yes
  roles:
    - role: k3s/master

- hosts: workers
  become: yes
  roles:
    - role: k3s/worker