---
apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
  name: bitwarden
spec:
  forceHttps: true
  providers: "UptimeRobot"
  url: https://bitwarden.technolab.cloud
  uptimeRobotConfig:
    interval: 300
    monitorType: http
    statusPages: "241496"
