---
apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
  name: plex
spec:
  forceHttps: true
  providers: "UptimeRobot"
  url: https://plex.technolab.cloud
  uptimeRobotConfig:
    interval: 300
    monitorType: "keyword"
    keywordExists: "yes"
    keywordValue: "404"
    statusPages: "241496"
