---
duplicati:
  image:
    repository: linuxserver/duplicati
    tag: version-v2.0.6.1-2.0.6.1_beta_2021-05-03
    pullPolicy: IfNotPresent

  strategy:
    type: Recreate

  env:
    TZ: Europe/Berlin
    PUID: 1001
    PGID: 1001

  service:
    main:
      ports:
        http:
          port: 8200

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx-internal
      hosts:
      - host: duplicati.home-lab.io
        paths:
        - path: /
          pathType: Prefix
      tls: []

  persistence:
    config:
      enabled: true
      existingClaim: nfs-pvc-duplicati
      emptyDir:
        enabled: false
      mountPath: /config
    source:
      enabled: true
      existingClaim: nfs-pvc-duplicati-source
      emptyDir:
        enabled: false
      mountPath: /source
    backups:
      enabled: false
      emptyDir:
        enabled: false
      mountPath: /backups
