---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-harbor-registry
  namespace: harbor
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
