version: "3"

services:
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: 
      - "--copy-service"
      - "--loglevel"
      - "debug"
    networks:
      - proxy
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpldapadmin.entrypoints=http"
      - "traefik.http.routers.phpldapadmin.rule=Host(`ldapadmin.local.technolab.cloud`)"
      - "traefik.http.middlewares.phpldapadmin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.phpldapadmin.middlewares=phpldapadmin-https-redirect"
      - "traefik.http.routers.phpldapadmin-secure.entrypoints=https"
      - "traefik.http.routers.phpldapadmin-secure.rule=Host(`ldapadmin.local.technolab.cloud`)"
      - "traefik.http.routers.phpldapadmin-secure.tls=true"
      - "traefik.http.routers.phpldapadmin-secure.service=phpldapadmin"
      - "traefik.http.services.phpldapadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
