---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo-cd
  name: sealed-secrets-controller
spec:
  project: default

  source:
    repoURL: https://github.com/ebrianne/k3s-at-home.git
    targetRevision: HEAD
    path: k3s/apps/kube-system/sealsecrets/
    helm:
      releaseName: sealed-secrets-controller
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
