---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-postgres
spec:
  storageClassName: ""
  claimRef:
    name: nfs-pvc-postgres
    namespace: database
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.40.2
    path: "/mnt/vault/Kubernetes/pvc/postgres"
