---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres
  name: postgres
  namespace: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres
