duckdns-go:
  duckdns:
    # required, need to be comma separated if more than one domain to update
    domains: "technolab"

  secret:
    existingSecret: true
    existingSecretName: "duckdns-secret"

  image:
    repository: ebrianne/duckdns-go
    tag: v1.0.3
    pullPolicy: IfNotPresent
    pullSecret: {}

  nameOverride: ""
  fullnameOverride: ""

  replicaCount: 1
  strategy:
    type: Recreate

  customLabels: {}

  extraEnvVars:
    TZ: Europe/Berlin

  podAnnotations: {}

  # Configure the Security Context for the main container
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector:
    kubernetes.io/arch: arm64

  tolerations: []
    # A list of tolerations to be applied to the Deployment.
    # Example:
    #   tolerations:
    #   - key: "node-role.kubernetes.io/infra-worker"
    #     operator: "Exists"
    #     effect: "NoSchedule"

  affinity: {}
    # An affinity stanza to be applied to the Deployment.
    # Example:
    #   affinity:
    #     nodeAffinity:
    #       requiredDuringSchedulingIgnoredDuringExecution:
    #         nodeSelectorTerms:
    #         - matchExpressions:
    #           - key: "node-role.kubernetes.io/infra-worker"
    #             operator: "Exists"
