---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo-cd
  name: code-server
spec:
  project: default

  source:
    repoURL: https://github.com/ebrianne/k3s-at-home.git
    targetRevision: HEAD
    path: k3s/apps/services/code-server/

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
