version: "3"

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.28.0
    container_name: prometheus
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    user: "65534:65534"
    volumes:
      - /home/ebrianne/prometheus/config:/etc/config
      - /home/ebrianne/prometheus/data:/data
    command:
      - '--storage.tsdb.retention.time=1h'
      - '--config.file=/etc/config/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--storage.tsdb.wal-compression'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=http"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.local.technolab.cloud`)"
      - "traefik.http.middlewares.prometheus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.prometheus.middlewares=prometheus-https-redirect"
      - "traefik.http.routers.prometheus-secure.entrypoints=https"
      - "traefik.http.routers.prometheus-secure.rule=Host(`prometheus.local.technolab.cloud`)"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
