---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-prometheus
  namespace: prometheus
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-prometheus
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
