---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: services-technolab-duckdns-org
  namespace: services
spec:
  dnsNames:
  - '*.technolab.duckdns.org'
  issuerRef:
    name: cert-manager-webhook-duckdns-production
    kind: ClusterIssuer
  secretName: services-technolab-duckdns-org-tls
