apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-calibre-web
spec:
  storageClassName: ""
  claimRef:
    name: nfs-pvc-calibre-web
    namespace: media
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.40.2
    path: "/mnt/vault/Kubernetes/pvc/calibre-web"
