---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-calibre-web
  namespace: media
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-calibre-web
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
