---
calibre-web:
  # helm install -n media calibre-web ./ -f values.yaml
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    repository: linuxserver/calibre-web
    pullPolicy: IfNotPresent
    tag: version-0.6.12

  strategy:
    type: Recreate

  env:
    TZ: Europe/Berlin
    PUID: "1001"
    PGID: "1001"
    # UMASK:
    DOCKER_MODS: "linuxserver/calibre-web:calibre"

  service:
    main:
      ports:
        http:
          port: 8083

  ingress:
    main:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx-internal
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: calibre-web.home-lab.io
          paths:
            - path: /

  persistence:
    config:
      enabled: false
      mountPath: /config
      type: pvc
      existingClaim: nfs-pvc-calibre-web

    books:
      enabled: false
      mountPath: /books
      type: pvc
      existingClaim: nfs-pvc-calibre-web
