---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAAzlmYiksH1rP/YpLgJ1K/5gzW2o55DcCHQ5UaZiqPJWdvt6794RDEsIIupUUKmn0orgEjROdcd+LgUV4ek0bCTMLpku1mdBU45iXg/Mq00Waur+hAYrF2+Wd4SeNz/OF7bbUF7l3zaecqbPWiKdsvB3HZAz07J/S5y7PyqdNiTlnnZoASwnf5DfW9vXACqEMfBDF/4uAuIxx8JKJavbrLcLoRceBPo7bRvLkU5RsY96eixWADjtQFoc7Kht03WFXxpkaoQ0O80FLtu06c/RScVosNBq7h6VOvAHaQR/6y8JJa0v9GA6+gQiFOCgLxoLlQ8hnKNiEHo1Wk28aimOUOUnzkPOqKOxcVeLYowyPKG44WE5PLJ3iURkFH/N/5syFhfpSCDb3TnuUjrpjWHObY8k0SWUnTcA7EznS77CqGqde2OhmJP7qxg5Jybr3lZ/ZlDaUU065fMt//XfPk51g6bF7N//SPGQl4alsBN/2TAzI6xO00pSTt5KoIsFK2rPO8cybSIVVM+h6p8UoPu6lN2GebgIzK3PC7wOC61OhkgozkZTfNwyX/NWX0Fzfgq8avTiP211IduEj9AF5ChlsJz5gDiVZamOMVQGWb5cmy0Gyl7qmpwMbST43Ut/5TmtjD1ASLBIrPpu6Uqa0fO/kxUjeA0ohdCjgsYVnk9nQkTw8UdR1td0WL0BpGCwM6Wj0Xw2IwnXl9vNmaewMDhRgfCwLZKlMI3HrjxF8BH99/IUZ34M3QYMoX
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
