---
- name: Check for k3s uninstall script
  stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: k3s_stat_result

- name: Uninstall k3s with the uninstall script
  shell: |
    sh /usr/local/bin/k3s-uninstall.sh
  when: k3s_stat_result.stat.exists == true

- name: Cleanup
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/k3s
    - "{{ systemd_dir }}/k3s"
    - "{{ systemd_dir }}/k3s-agent"
    - /etc/rancher/k3s
    - /var/lib/rancher/k3s
    - /etc/modules-load.d/overlay.conf
    - /etc/modules-load.d/br_netfilter.conf
    - /etc/sysctl.d/kube.conf
    
- name: Reboot the machine
  reboot:
    reboot_timeout: 3600
