---
- name: Install some packages
  apt:
    name: curl,htop,open-iscsi,nfs-common,zsh
    state: present

- name: Copy kube module file
  template:
    src: mod.kube.conf.j2
    dest: /etc/modules-load.d/kube.conf
    owner: root
    group: root
    mode: 0600

- name: Copy kube sysctl file
  template:
    src: kube.conf.j2
    dest: /etc/sysctl.d/kube.conf
    owner: root
    group: root
    mode: 0600

- name: Disable IPv6
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "1"
    state: present
    reload: yes

- name: Remove swap
  shell: |
    swapoff -a

- name: Disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Delete swap.img file
  file:
    path: /swap.img
    state: absent

- name: Reboot
  reboot:
    reboot_timeout: 3600
