---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: services
  labels:
    app: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
      annotations: {}
    spec:
      containers:
      - name: plex
        image: plexinc/pms-docker:1.22.0.4163-d8c4875dd
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /identity
            port: 32400
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        startupProbe:
          httpGet:
            path: /identity
            port: 32400
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        ports:
        - containerPort: 32400
          name: pms
          protocol: TCP
        env:
        - name: TZ
          value: Europe/Berlin
        - name: PLEX_CLAIM
          valueFrom:
            secretKeyRef:
              name: plex-secret
              key: claim-token
        - name: PLEX_UID
          value: "1001"
        - name: PLEX_GID
          value: "1001"
        - name: VERSION
          value: "docker"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: tv
          mountPath: /data/tv
        - name: music
          mountPath: /data/music
        - name: movies
          mountPath: /data/movies
        - name: transcode
          mountPath: /transcode
        resources: {}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: nfs-pvc-plex
      - name: transcode
        emptyDir: {}
      - name: tv
        nfs:
          server: 10.0.40.2
          path: "/mnt/vault/Media/Series"
      - name: movies
        nfs:
          server: 10.0.40.2
          path: "/mnt/vault/Media/Movies"
      - name: music
        nfs:
          server: 10.0.40.2
          path: "/mnt/vault/Media/Music"
