---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: plex
  name: plex
  namespace: services
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    external-dns.alpha.kubernetes.io/hostname: plex.technolab.cloud
    external-dns.alpha.kubernetes.io/target: technolab.cloud
spec:
  rules:
  - host: plex.technolab.cloud
    http:
      paths:
      - path:
        backend:
          serviceName: plex
          servicePort: 32400
  tls:
  - hosts:
    - plex.technolab.cloud
    secretName: services-technolab-cloudflare-org-tls
