---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-plex
  namespace: services
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-plex
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
