---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    # renovate: registryUrl=https://grafana.github.io/helm-charts
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.4.2
    chart: grafana
    helm:
      releaseName: grafana
      values: |
        ---
        image:
          pullPolicy: IfNotPresent

        downloadDashboardsImage:
          pullPolicy: IfNotPresent

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          labels: {}
          path: /
          hosts:
            - grafana.home-lab.io

        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi

        persistence:
          enabled: true
          existingClaim: longhorn-pvc-grafana

        initChownData:
          enabled: true

          image:
            pullPolicy: IfNotPresent

        admin:
          existingSecret: "grafana-secret"
          userKey: admin-user
          passwordKey: admin-password

        plugins:
          - grafana-clock-panel
          - grafana-worldmap-panel
          - grafana-piechart-panel

        grafana.ini:
          paths:
            data: /var/lib/grafana/data
            logs: /var/log/grafana
            plugins: /var/lib/grafana/plugins
            provisioning: /etc/grafana/provisioning
          analytics:
            check_for_updates: true
          log:
            mode: console
          grafana_net:
            url: https://grafana.net

        ldap:
          enabled: false
  destination:
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
