---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-grafana
  namespace: grafana
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
