# Source: phpldapadmin/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpldapadmin-config
  namespace: ldap
  labels:
    app: phpldapadmin
data:
  PHPLDAPADMIN_LDAP_HOSTS: "openldap:1389"
  PHPLDAPADMIN_HTTPS: "false"
  PHPLDAPADMIN_TRUST_PROXY_SSL: "true"