---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-grafana
  namespace: grafana
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-grafana
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
