---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBsLkYyv5+dGVzjpygor8ORgcx6rgJeNRsOWnfGkWpgJL7rFP+ttK5Fq/WACxnWpR+NheUBu8SAUYSD2v2cxIblTPbXCOEbocoB6+Q7FiiuJZzyDZo79hhQdSYjjJwt8E11GEBSeWZGDGVtwwGy/GAN/p7l+0c/PcsKQpYASQBQ7Sy2NVP87AfsTpFJfKD7k5zLrTJFbwiC1BY41KfOzZHbOk+ax9U4RFDxGBZ9N4EvmiPi7mRp+4ZXC2+fZoPOoBQvHqY4nQRM7+1gC9xYdOt5xYGXK8Vh4qlzuXyFQUOVzJucAYEAnHnrFRh5CGnDFqntZmREjedbLiCBvrWakMsM5P3JqyKTZRWh+wifVI89DLBweaK+DPxZhhzHdJOIFxdhB6+jWvX1YlJmIKYlW0U73Q11sM9ijFrdWe54Bnhg30dNIuwMzTdZEn3QNT9srtY420/tFccez3uF+ffVwWOGuAsGO19lwP/bQJDfq66e9q2kF0mwswUCc5gyOE3Yy/SKBV0iP3NT8yw+2FqNdiv1qtUnDu/AwFssZytwIBn4z9fX9l2lFrxOIbo9N5g5FbySc496rFKOuT3MDGRxkd4R4LJhVDZ+Rb4hU7OpirvyaJwGLm1K8MPapOwu3pkvvcZS+7GhMOWT2NiXQCvUm0szs7UiOAQZ4yBaRajJuR7upATx54Zz3eiTaWO1/4a7VpMr5Nn7OA==
    admin-user: AgBCz0C17Tf3jB0NBemxskkp/66q290PZBXJZ8AD2KPfEZvkNHeP2sZvfPZOw4C/bBgls2CIc5hxHbMx1JD9l59Nu6Hq/H58cKPWPaeQpLweI0/m3o9DU+RbXEpRPY/Pnn4ImkQ8gvk9BnyJ6NI8OKVwFZZzAafi8uIOko1Df2M0kRHzuwXVpezlBOO9ce1opAPnKJg0Dqo2l7N6wp4FCrL6jS8zN0e2n/rYsj4ezt3RiAfk8rlZ73HdmmPM97dv7+ETyBjZLwQdRQ+H+n9Gh6PoTuxWqX9Rxbqe3Rzjn5V/m+/870ECgXLm4FjxS4GYK5Sk0gEb7FPkSCwbvl6ZrarxEUrvUGkZAwQ0jd+GDQgfXvbAJNfx0/f1CRuUEEICTU2qaOvgESJ3aB9xbceMoFqOAizGXYJunrvXTiBWxMftRMkfKIyRJsRr3WE/TLYOgy+KZSecduD49EA6b/CUYqWYJsariGm+0Gi0C3/9Hg0p4wY2ucJ66i/1DAPKiZEjElixMJfnV8KBce7ele+DJUBBIMuwZsuWBmbOvovKIIDz5AWmtAcpXscNGQNZyCpz2c1JZh3nz/JJQpVdNsvP8zDFViMyao3khAnr0Vg0wNDuTBYq8FJByeXCWBsCZjcVypr1np1ExqjTtP+BBZximkrna+bCFZU4VNNGgcxe51b936uC/M+V0ACDPrq3LUhcUxd6NLG99A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: grafana
    type: Opaque
