version: "3"

services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr:version-v0.9.5
    container_name: bazarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Europe/Berlin
    volumes:
      - /home/ebrianne/bazarr/data:/config
      - /nfs/Media/Movies:/movies
      - /nfs/Media/Series:/tv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.entrypoints=http"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.local.technolab.cloud`)"
      - "traefik.http.middlewares.bazarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bazarr.middlewares=bazarr-https-redirect"
      - "traefik.http.routers.bazarr-secure.entrypoints=https"
      - "traefik.http.routers.bazarr-secure.rule=Host(`bazarr.local.technolab.cloud`)"
      - "traefik.http.routers.bazarr-secure.tls=true"
      - "traefik.http.routers.bazarr-secure.service=bazarr"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
