---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-prometheus
  namespace: prometheus
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
