---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
  labels:
    app: redis
data:
  redis.conf: |-
    bind 0.0.0.0
    appendonly yes
    # Other cluster members need to be able to connect
    protected-mode no
