---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-redis
  namespace: redis
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
