---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddclient-cloudflare
  namespace: default
  labels:
    app: ddclient
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: ddclient
  template:
    metadata:
      labels:
        app: ddclient
    spec:
      containers:
        - name: ddclient
          image: linuxserver/ddclient:version-v3.9.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /config
              name: ddclient-config-file
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: ddclient-config-file
          secret:
            secretName: ddclient-config-secret
