---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: bitwardenrs
  name: bitwarden-ing-admin
  namespace: services
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: "http://authelia.services.svc.cluster.local/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://authelia.technolab.cloud/"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    external-dns.alpha.kubernetes.io/hostname: bitwarden.technolab.cloud
    external-dns.alpha.kubernetes.io/target: technolab.cloud
spec:
  rules:
  - host: bitwarden.technolab.cloud
    http:
      paths:
      - path: /admin
        backend:
          serviceName: bitwarden-bitwardenrs
          servicePort: 8443
  tls:
  - hosts:
    - bitwarden.technolab.cloud
    secretName: services-technolab-cloudflare-org-tls
