---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: cert-manager-webhook-duckdns
spec:
  project: default

  source:
    repoURL: https://github.com/ebrianne/k3s-at-home.git
    targetRevision: HEAD
    path: apps/cert-manager/cert-manager-webhook-duckdns/
    helm:
      releaseName: cert-manager-webhook-duckdns
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
